#!/usr/bin/env node
/**
 * Package Metadata Generator
 *
 * This script generates metadata from actual source code exports, ensuring
 * documentation stays in sync with the library implementation.
 *
 * Run: npx tsx scripts/generate-package-metadata.ts
 *
 * Generates: src/app/core/config/packages.generated.ts
 */

/* oxlint-disable no-console */

import * as fs from 'node:fs';
import * as path from 'node:path';

interface PackageMetadata {
  serviceCount: number;
  injectFnCount: number;
  experimentalServiceCount: number;
  services: string[];
  injectFunctions: string[];
  experimentalServices: string[];
  version: string;
}

function extractExportsFromPublicApi(filePath: string): string[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const exports: string[] = [];

  // Match: export { ServiceName } from './path'
  const exportRegex = /export\s*\{\s*([^}]+)\}\s*from/g;
  let match;

  while ((match = exportRegex.exec(content)) !== null) {
    const exportedNames = match[1]
      .split(',')
      .map((n) => n.trim())
      .filter((n) => n.length > 0);
    exports.push(...exportedNames);
  }

  return exports;
}

function countServicesInDirectory(dirPath: string): { services: string[]; count: number } {
  const services: string[] = [];

  if (!fs.existsSync(dirPath)) {
    return { services: [], count: 0 };
  }

  const files = fs.readdirSync(dirPath);

  for (const file of files) {
    if (file.endsWith('.service.ts')) {
      const serviceName = file.replace('.service.ts', '');
      // Convert kebab-case to PascalCase for service name
      const pascalName = serviceName
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
      services.push(`${pascalName}Service`);
    }
  }

  return { services, count: services.length };
}

function countInjectFunctionsInDirectory(dirPath: string): { functions: string[]; count: number } {
  const functions: string[] = [];

  if (!fs.existsSync(dirPath)) {
    return { functions: [], count: 0 };
  }

  const files = fs.readdirSync(dirPath);

  for (const file of files) {
    if (file.startsWith('inject-') && file.endsWith('.ts')) {
      const fnName = file.replace('.ts', '');
      functions.push(fnName);
    }
  }

  return { functions, count: functions.length };
}

function getExperimentalServices(): string[] {
  const experimentalDir = 'packages/browser-web-apis/experimental/src';
  const { services } = countServicesInDirectory(experimentalDir);
  return services;
}

function generateMetadata(): PackageMetadata {
  const browserWebApisDir = 'packages/browser-web-apis/src';
  const experimentalDir = 'packages/browser-web-apis/experimental/src';

  // Count services (main + experimental)
  const mainServices = countServicesInDirectory(`${browserWebApisDir}/services`);
  const experimentalServices = getExperimentalServices();
  const totalServices = mainServices.count + experimentalServices.length;

  // Count inject functions (main + experimental)
  const mainInjectFns = countInjectFunctionsInDirectory(`${browserWebApisDir}/fns`);
  const experimentalInjectFns = countInjectFunctionsInDirectory(experimentalDir);
  const totalInjectFns = mainInjectFns.count + experimentalInjectFns.count;
  const allInjectFns = [...mainInjectFns.functions, ...experimentalInjectFns.functions];

  // Get version from package.json
  const packageJson = JSON.parse(
    fs.readFileSync('packages/browser-web-apis/package.json', 'utf-8'),
  );

  return {
    serviceCount: totalServices,
    injectFnCount: totalInjectFns,
    experimentalServiceCount: experimentalServices.length,
    services: mainServices.services,
    injectFunctions: allInjectFns,
    experimentalServices,
    version: packageJson.version || 'unknown',
  };
}

function generateTypeScriptFile(metadata: PackageMetadata): string {
  return `// Auto-generated by scripts/generate-package-metadata.ts
// Do not edit manually - run: npx tsx scripts/generate-package-metadata.ts

export const GENERATED_METADATA = {
  version: '${metadata.version}',
  browserWebApis: {
    serviceCount: ${metadata.serviceCount},
    injectFnCount: ${metadata.injectFnCount},
    experimentalServiceCount: ${metadata.experimentalServiceCount},
    services: ${JSON.stringify(metadata.services, null, 2)},
    injectFunctions: ${JSON.stringify(metadata.injectFunctions, null, 2)},
    experimentalServices: ${JSON.stringify(metadata.experimentalServices, null, 2)},
  },
} as const;

// Convenience exports
export const SERVICE_COUNT = GENERATED_METADATA.browserWebApis.serviceCount;
export const INJECT_FN_COUNT = GENERATED_METADATA.browserWebApis.injectFnCount;
export const EXPERIMENTAL_COUNT = GENERATED_METADATA.browserWebApis.experimentalServiceCount;
`;
}

function main(): void {
  console.log('🔍 Generating package metadata from source code...\n');

  const metadata = generateMetadata();

  const mainInjectCount = metadata.injectFunctions.filter((f) => !f.includes('idle')).length;
  const experimentalInjectCount = metadata.injectFunctions.filter((f) => f.includes('idle')).length;

  console.log(`📦 browser-web-apis v${metadata.version}`);
  console.log(`   Services: ${metadata.serviceCount}`);
  console.log(`   - Main: ${metadata.services.length}`);
  console.log(`   - Experimental: ${metadata.experimentalServiceCount}`);
  console.log(`   Inject Functions: ${metadata.injectFnCount}`);
  console.log(`   - Main: ${mainInjectCount}`);
  console.log(`   - Experimental: ${experimentalInjectCount}\n`);

  const outputPath = 'src/app/core/config/packages.generated.ts';
  const content = generateTypeScriptFile(metadata);

  fs.writeFileSync(outputPath, content, 'utf-8');

  console.log(`✅ Generated: ${outputPath}`);
  console.log('\nNext steps:');
  console.log('  1. Import from packages.generated.ts in packages.data.ts');
  console.log('  2. Update HOME_STATS to use INJECT_FN_COUNT');
  console.log('  3. Run: npm run test:docs-consistency');
}

main();
